/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author adria
 */
public class SnowFlakeForm extends java.awt.Frame {

    /**
     * Creates new form dssef
     */
    public SnowFlakeForm() {
        initComponents();
        bGenerate.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        snowFlakePanel = new SnowFlakePanel();
        ButtonsPanel = new javax.swing.JPanel();
        bCut = new javax.swing.JButton();
        bGenerate = new javax.swing.JButton();
        bSavePoints = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1024, 768));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        add(snowFlakePanel, java.awt.BorderLayout.CENTER);

        ButtonsPanel.setLayout(new java.awt.GridLayout(5, 0));

        bCut.setText("Cut Triangle");
        bCut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCutActionPerformed(evt);
            }
        });
        ButtonsPanel.add(bCut);

        bGenerate.setText("Generate SnowFlake");
        ButtonsPanel.add(bGenerate);

        bSavePoints.setText("Save Points");
        bSavePoints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSavePointsActionPerformed(evt);
            }
        });
        ButtonsPanel.add(bSavePoints);

        add(ButtonsPanel, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void bCutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCutActionPerformed
        bGenerate.setEnabled(true);
        snowFlakePanel.taglia();
        bCut.setEnabled(false);
    }//GEN-LAST:event_bCutActionPerformed

    private void bSavePointsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSavePointsActionPerformed
        snowFlakePanel.savePoints();
    }//GEN-LAST:event_bSavePointsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SnowFlakeForm().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonsPanel;
    private javax.swing.JButton bCut;
    private javax.swing.JButton bGenerate;
    private javax.swing.JButton bSavePoints;
    private SnowFlakePanel snowFlakePanel;
    // End of variables declaration//GEN-END:variables
}
